language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: k4KoaxO/79A76RCvz+xnXrmJjnyXp0og5HO0Dbd2QwSQ4m9Chh4y0geKLnmei0EuzxQggj4rfOUDgH7Oo4knjLKkfEmKHo0mvxDxHDGYVbiNpEiNtRJ3FnnO0z8CaGX/L3R5HDa6qAG11r2RiA61GtJAnrPZZN8Sx+eayF21m/I=
  - secure: Xk+HIIVjSyqEx/vRw37RK+YkoAhfuEqgCKEM9+wAHoTGNyreTSfsNvx9EiND3HL0zBJrhAaF2VZmbF10gTxlJ3R8Iri7bsn+S/aum5R3L8TE0yVbz9y8uqH3O1M5k8LzmewY5y7ThAACUwZYF2fHMV1/G+Nb8BEbTvUBY3/49XM=
  - secure: WHdCN1eytNsHeCYcJeZaxGwgAltYyxlcuYDSrj6wX4KfWE/E7yvskj8hV7F/us5NN6j2LjVH/W7pan/NKaAxo6lBPXrnA5SvVKipSByR7BQdoD+CxPKkRtQe0fdlmCZsFMpWwiRTT2Iy6m7nPlbeF3FxfSX2wsUKlNoSC4T3IqU=
  - secure: Qcs2Xr5DqBfZlbIYF1GzpHL6+k4mSu1EJ1PhgTwEZws63WJshzHMUkW9s9BTb/p0mzfNoSWqxSlkyypOD07mf9WXoaXL6FBh8yIvc83sm//YtHMXsIWsKtIxrvv7b75TZ9jF9uSRGeIV3YzsKNudxlhOWdTEwJfT/3z5kIB32kY=
